### ISSUE TITLE
Circular dependencies need to be fixed

### ISSUE THREAD

**Issue by AndrewFarley** [Couchers-org/web-frontend#16]
Because there are circular dependancies there is memory leaks and constantly increasing memory usage of Next.js.  After some research this appears to be related to and/or because of..

https://github.com/vercel/next.js/issues/34659
https://github.com/nodejs/node/issues/42080

I used an wonderful tool to help figure this out called [madge](https://www.npmjs.com/package/madge) and ran it with the following command...

```bash
npx madge   -c --extensions ts,tsx --exclude "test*" -l dot --dot  -i test.png ./
```

Which outputs the file explaining the circular dependencies...

![circular-deps](https://user-images.githubusercontent.com/470163/170853252-dcdc28ac-3767-4cc3-9f76-cff8ddc1222c.png)

I might also recommend to after fixing our circular deps, to integrate this tool into our testing and to basically fail out and don't let new code with circular dependencies to be merged into master.

**Comment by darrenvong** [comment]
Is this actually happening in production? Hot reload should not be enabled/used in production as it's mainly for fast feedback during development when we change some code. It creates some impossible scenarios like loading modules multiple times and so we may be better off disabling that first, then fix the circular imports.

**Comment by AndrewFarley** [comment]
Because we no longer use dependencies/modules in production I'm going to close this.  Can re-open at a later time if needed.
