### ISSUE TITLE
Make mark all as read button clearer

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/web-frontend#180]
It needs to be a text label or something - seems a lot of people don't know it's there.

![image](https://user-images.githubusercontent.com/32044095/187645701-e46efe37-fe91-4b68-b54c-19d4fb3764dc.png)

**Comment by bakeiro** [comment]
Hi!

just saw this issue... can should be a label with some text in specific??

thanks :)

**Comment by Roshanjossey** [comment]
This looks done with #203

**Comment by bakeiro** [comment]
true, closed now
