### ISSUE TITLE
Upon uploading event photo, preview on event editing page is not displayed as it will appear on event page

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/web-frontend#83]
After uploading an image for an event, the photo is not displayed as it will appear on the event page.

Here is how it looks on the event editing page:
![image](https://user-images.githubusercontent.com/79384268/134428418-22a537b3-87c0-414c-b69a-eb88afaf0eac.png)

Here is how it looks on the event page:
![image](https://user-images.githubusercontent.com/79384268/134741067-2bccfccb-dec2-495e-89b3-1ed4ac11a8fc.png)

As you can see from the screenshots above, the image appears much smaller and in a different ratio on the event editing page compared to when it is displayed on the event page.

It is very helpful for organizers to have the image displayed consistently across platforms (desktop, mobile, native app) and be able to see what that image will look like in all of those places as the image is one of the things that draws people's attention to the event.

**Comment by bakeiro** [comment]
if nobody is assigned for this task, I can take it :)

**Comment by bakeiro** [comment]
Branch merged ;)
